#!/bin/sh

system_type=$(uname -s)

echo "Bootstrapping for system type $system_type"

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update
    sudo apt-get install zsh-autosuggestions zsh-syntax-highlighting zsh -y
fi

if command -v pacman >/dev/null 2>&1; then
    sudo pacman -Syu zsh-autosuggestions zsh-syntax-highlighting zsh --noconfirm
fi

echo "Changing shell to zsh"
chsh -s `which zsh`
echo "you may need to relog for changes to take effect"
